language: ruby
rvm:
    - 2.1.7
script:
    - RAILS_ENV=test bundle exec rake db:migrate --trace
    - bundle exec rake db:test:prepare
    - bundle exec rake spec
before_script:
    
    - psql -c 'create database myapp_test;' -U postgres
    - bundle exec rake assets:precompile
    
install:
    - bundle _1.10.6_ install