language: ruby
rvm:
    - 2.1.7
script:
    - RAILS_ENV=test bundle exec rake db:migrate --trace
    - bundle exec rake spec
before_script:
    
    - psql -c 'create database myapp_test;' -U postgres
    - bundle exec rake assets:precompile
    
before_install:
    - rvm @global do gem uninstall bundle -a -x
    - rvm @global do gem install bundler -v 1.10.6